### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by circuitry2** [zyra/ionic-super-tabs-example#20]
Updating the submodule fails so I cannot run the example:

#: ~/src/ionic2-super-tabs-example
→ git submodule init && git submodule update
error: no such remote ref bc9fd8dc35db502b2f47aeb103c061ed16807a49
Fetched in submodule path 'src/ionic2-super-tabs', but it did not contain bc9fd8dc35db502b2f47aeb103c061ed16807a49. Direct fetching of that commit failed.

**Comment by flistefliste** [comment]
same here

**Comment by ihadeed** [comment]
I use submodules because it makes development much easier. 

If you're experiencing issues with them, you can delete `src/ionic2-super-tabs` and then clone the repo into that same path by running `git clone https://github.com/zyra/ionic2-super/tabs src/ionic2-super-tabs`.

Alternatively, you can install `ionic2-super-tabs` from npm and update all references to use `ionic2-super-tabs` instead of the local version.

**Comment by JeongYoungHo** [comment]
@circuitry2 @flistefliste 
delete `src/ionic2-super-tabs`
same path `git clone https://github.com/zyra/ionic2-super-tabs src/ionic2-super-tabs`
`git submodule update`
this works well.
thank you @ihadeed

**Comment by naguchennai** [comment]
app-scripts]     at new BuildError (C:\New folder\IONIC\ionic2-super-tabs-example-master\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
[app-scripts]     at Timeout._onTimeout (C:\New folder\IONIC\ionic2-super-tabs-example-master\node_modules\@ionic\app-scripts\dist\watch.js:71:20)
[app-scripts]     at ontimeout (timers.js:436:11)
[app-scripts]     at tryOnTimeout (timers.js:300:5)
[app-scripts]     at listOnTimeout (timers.js:263:5)
[app-scripts]     at Timer.processTimers (timers.js:223:10)
[app-scripts] (node:15072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise
which was not handled with .catch(). (rejection id: 1)
